# -*- coding:utf-8 -*-

CREATE_DATABASE = '''CREATE DATABASE `minitask`'''

CREATE_TABLE = '''CREATE TABLE `video_info`(
`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`pic` VARCHAR(255) NOT NULL DEFAULT '',
`mov` INT NOT NULL DEFAULT 0,
`description` VARCHAR(255) NOT NULL DEFAULT ''
,`plays` INT NOT NULL DEFAULT 0,
`create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`upper` VARCHAR(255) NOT NULL DEFAULT '',
`duration` INT NOT NULL,
`site_src` VARCHAR(255) NOT NULL DEFAULT ''
)ENGINE=InnoDB CHARSET=utf8'''
